# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-monitoring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: endpoint-monitoring-operator
  template:
    metadata:
      labels:
        name: endpoint-monitoring-operator
    spec:
      serviceAccountName: endpoint-monitoring-operator
      containers:
        - name: endpoint-monitoring-operator
          # Replace this with the built image name
          image: {REPLACE_WITH_OPERATOR_IMAGE}
          command:
          - endpoint-monitoring-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPERATOR_NAME
              value: "endpoint-monitoring-operator"
            - name: COLLECTOR_IMAGE
              value: {REPLACE_WITH_METRICS_COLLECTOR_IMAGE}
